version: '3.8'

services:
  db-pg:
    image: bitnami/postgresql
    container_name: postgresql
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/bitnami/postgresql

    environment:
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_DATABASE=apisolid
